More informative errors when multiple/no jars can be found

diff --git a/bin/run-example b/bin/run-example
--- a/bin/run-example
+++ b/bin/run-example
@@ -40,14 +40,24 @@ fi
 # Figure out the JAR file that our examples were packaged into. This includes a bit of a hack
 # to avoid the -sources and -doc packages that are built by publish-local.
 EXAMPLES_DIR="$FWDIR"/examples
-SPARK_EXAMPLES_JAR=""
-if [ -e "$EXAMPLES_DIR"/target/scala-$SCALA_VERSION/*assembly*[0-9Tg].jar ]; then
-  export SPARK_EXAMPLES_JAR=`ls "$EXAMPLES_DIR"/target/scala-$SCALA_VERSION/*assembly*[0-9Tg].jar`
-fi
 if [[ -z $SPARK_EXAMPLES_JAR ]]; then
-  echo "Failed to find Spark examples assembly in $FWDIR/examples/target" >&2
-  echo "You need to build Spark with sbt/sbt assembly before running this program" >&2
-  exit 1
+  jars_pat="$EXAMPLES_DIR/target/scala-$SCALA_VERSION/*assembly*[0-9Tg].jar"
+  SPARK_EXAMPLES_JAR=( $jars_pat )
+  num_jars=${#SPARK_EXAMPLES_JAR[@]}
+
+  if (( $num_jars == 0 )); then
+    echo "Failed to find Spark examples assembly matching $jars_pat" >&2
+    echo "You need to build Spark with sbt/sbt assembly before running this program" >&2
+    exit 1
+  fi
+
+  if (( $num_jars > 1 )); then
+    echo -e "Found multiple jars matching $jars_pat" >&2
+    echo "Please remove all but one, or set SPARK_EXAMPLES_JAR explicitly." >&2
+    exit 1
+  fi
+
+  export SPARK_EXAMPLES_JAR=$SPARK_EXAMPLES_JAR[0]
 fi
 
 
diff --git a/bin/spark-class b/bin/spark-class
--- a/bin/spark-class
+++ b/bin/spark-class
@@ -109,17 +109,19 @@ export JAVA_OPTS
 
 if [ ! -f "$FWDIR/RELEASE" ]; then
   # Exit if the user hasn't compiled Spark
-  num_jars=$(ls "$FWDIR"/assembly/target/scala-$SCALA_VERSION/ | grep "spark-assembly.*hadoop.*.jar" | wc -l)
-  jars_list=$(ls "$FWDIR"/assembly/target/scala-$SCALA_VERSION/ | grep "spark-assembly.*hadoop.*.jar")
-  if [ "$num_jars" -eq "0" ]; then
-    echo "Failed to find Spark assembly in $FWDIR/assembly/target/scala-$SCALA_VERSION/" >&2
+  jars_pat="$FWDIR/assembly/target/scala-$SCALA_VERSION/spark-assembly*hadoop*.jar"
+  shopt -s nullglob
+  jars_list=( $jars_pat )
+  num_jars=${#jars_list[@]}
+
+  if (( $num_jars == 0 )); then
+    echo "Failed to find Spark assembly matching $jars_pat" >&2
     echo "You need to build Spark with 'sbt/sbt assembly' before running this program." >&2
     exit 1
   fi
-  if [ "$num_jars" -gt "1" ]; then
-    echo "Found multiple Spark assembly jars in $FWDIR/assembly/target/scala-$SCALA_VERSION:" >&2
-    echo "$jars_list"
-    echo "Please remove all but one jar."
+  if (( $num_jars > 1 )); then
+    echo "Found multiple Spark assembly jars matching $jars_pat" >&2
+    echo "Please remove all but one jar." >&2
     exit 1
   fi
 fi
