Revert "Merge remote-tracking branch 'apache/master'"
This reverts commit 263178b100563d5b6baa6081bb8069ccc77ea8bb, reversing
changes made to df4da606cb5db531efd885051f8a320bc8a5cb2f.

diff --git a/dev/check-license b/dev/check-license
--- a/dev/check-license
+++ b/dev/check-license
@@ -24,27 +24,29 @@ acquire_rat_jar () {
 
   JAR="$rat_jar"
 
-  # Download rat launch jar if it hasn't been downloaded yet
-  if [ ! -f "$JAR" ]; then
-    # Download
-    printf "Attempting to fetch rat\n"
-    JAR_DL="${JAR}.part"
-    if [ $(command -v curl) ]; then
-      curl -L --silent "${URL}" > "$JAR_DL" && mv "$JAR_DL" "$JAR"
-    elif [ $(command -v wget) ]; then
-      wget --quiet ${URL} -O "$JAR_DL" && mv "$JAR_DL" "$JAR"
-    else
-      printf "You do not have curl or wget installed, please install rat manually.\n"
+  if [[ ! -f "$rat_jar" ]]; then
+    # Download rat launch jar if it hasn't been downloaded yet
+    if [ ! -f "$JAR" ]; then
+      # Download
+      printf "Attempting to fetch rat\n"
+      JAR_DL="${JAR}.part"
+      if [ $(command -v curl) ]; then
+        curl -L --silent "${URL}" > "$JAR_DL" && mv "$JAR_DL" "$JAR"
+      elif [ $(command -v wget) ]; then
+        wget --quiet ${URL} -O "$JAR_DL" && mv "$JAR_DL" "$JAR"
+      else
+        printf "You do not have curl or wget installed, please install rat manually.\n"
+        exit -1
+      fi
+    fi
+
+    unzip -tq $JAR &> /dev/null
+    if [ $? -ne 0 ]; then
+      # We failed to download
+      printf "Our attempt to download rat locally to ${JAR} failed. Please install rat manually.\n"
       exit -1
     fi
-  fi
-
-  unzip -tq "$JAR" &> /dev/null
-  if [ $? -ne 0 ]; then 
-    # We failed to download
-    rm "$JAR"
-    printf "Our attempt to download rat locally to ${JAR} failed. Please install rat manually.\n"
-    exit -1
+    printf "Launching rat from ${JAR}\n"
   fi
 }
 
@@ -68,11 +70,6 @@ mkdir -p "$FWDIR"/lib
 }
 
 $java_cmd -jar "$rat_jar" -E "$FWDIR"/.rat-excludes  -d "$FWDIR" > rat-results.txt
-
-if [ $? -ne 0 ]; then
-   echo "RAT exited abnormally"
-   exit 1
-fi
 
 ERRORS="$(cat rat-results.txt | grep -e "??")"
 
