Disable all checks for now

diff --git a/dev/lint-python b/dev/lint-python
--- a/dev/lint-python
+++ b/dev/lint-python
@@ -22,6 +22,7 @@ SPARK_ROOT_DIR="$(dirname "$SCRIPT_DIR")"
 PATHS_TO_CHECK="./python/pyspark/ ./ec2/spark_ec2.py ./examples/src/main/python/ ./dev/sparktestsupport"
 PATHS_TO_CHECK="$PATHS_TO_CHECK ./dev/run-tests.py ./python/run-tests.py"
 PYTHON_LINT_REPORT_PATH="$SPARK_ROOT_DIR/dev/python-lint-report.txt"
+PYLINT_REPORT_PATH="$SPARK_ROOT_DIR/dev/pylint-report.txt"
 
 cd "$SPARK_ROOT_DIR"
 
@@ -47,29 +48,6 @@ if [ ! -e "$PEP8_SCRIPT_PATH" ]; then
     fi
 fi
 
-# There is no need to write this output to a file
-#+ first, but we do so so that the check status can
-#+ be output before the report, like with the
-#+ scalastyle and RAT checks.
-python "$PEP8_SCRIPT_PATH" --ignore=E402,E731,E241,W503,E226 $PATHS_TO_CHECK >> "$PYTHON_LINT_REPORT_PATH"
-pep8_status="${PIPESTATUS[0]}"
-
-if [ "$compile_status" -eq 0 -a "$pep8_status" -eq 0 ]; then
-    lint_status=0
-else
-    lint_status=1
-fi
-
-if [ "$lint_status" -ne 0 ]; then
-    echo "Python lint checks failed."
-    cat "$PYTHON_LINT_REPORT_PATH"
-else
-    echo "Python lint checks passed."
-fi
-
-# rm "$PEP8_SCRIPT_PATH"
-rm "$PYTHON_LINT_REPORT_PATH"
-
 # Easy install pylint in /dev/pylint. To easy_install into a directory, the PYTHONPATH should
 # be set to the directory.
 # dev/pylint should be appended to the PATH variable as well.
@@ -87,9 +65,42 @@ if [ ! -d "$PYLINT_HOME" ]; then
     fi
 fi
 
-# for to_be_checked in "$PATHS_TO_CHECK"
-# do
-#     pylint --rcfile="$PYLINT_HOME/pylintrc" $to_be_checked
-# done
+# There is no need to write this output to a file
+#+ first, but we do so so that the check status can
+#+ be output before the report, like with the
+#+ scalastyle and RAT checks.
+python "$PEP8_SCRIPT_PATH" --ignore=E402,E731,E241,W503,E226 $PATHS_TO_CHECK >> "$PYTHON_LINT_REPORT_PATH"
+pep8_status="${PIPESTATUS[0]}"
+
+if [ "$compile_status" -eq 0 -a "$pep8_status" -eq 0 ]; then
+    lint_status=0
+else
+    lint_status=1
+fi
+
+if [ "$lint_status" -ne 0 ]; then
+    echo "PEP8 checks failed."
+    cat "$PYTHON_LINT_REPORT_PATH"
+else
+    echo "PEP8 checks passed."
+fi
+
+rm "$PYTHON_LINT_REPORT_PATH"
+
+
+for to_be_checked in "$PATHS_TO_CHECK"
+do
+    pylint --rcfile="$PYLINT_HOME/pylintrc" $to_be_checked >> "$PYLINT_REPORT_PATH"
+done
+
+if [ "${PIPESTATUS[0]}" -ne 0 ]; then
+    lint_status=0
+    echo "Pylint checks failed."
+    cat "$PYLINT_REPORT_PATH"
+else
+    echo "Pylint checks passed."
+fi
+
+rm "$PYLINT_REPORT_PATH"
 
 exit "$lint_status"
