[SPARK-23367][Build] Include python document style checking

diff --git a/dev/lint-python b/dev/lint-python
--- a/dev/lint-python
+++ b/dev/lint-python
@@ -27,6 +27,7 @@ PYDOCSTYLE_REPORT_PATH="$SPARK_ROOT_DIR/dev/pydocstyle-report.txt"
 PYLINT_REPORT_PATH="$SPARK_ROOT_DIR/dev/pylint-report.txt"
 PYLINT_INSTALL_INFO="$SPARK_ROOT_DIR/dev/pylint-info.txt"
 PYDOCSTYLEBUILD="pydocstyle"
+PYDOCSTYLEVERSION=$(python -c 'import pkg_resources; print pkg_resources.get_distribution("pydocstyle").version')
 SPHINXBUILD=${SPHINXBUILD:=sphinx-build}
 
 SPHINX_REPORT_PATH="$SPARK_ROOT_DIR/dev/sphinx-report.txt"
@@ -88,23 +89,27 @@ fi
 
 # Check python document style, skip check if pydocstyle is not installed.
 if hash "$PYDOCSTYLEBUILD" 2> /dev/null; then
-    pydocstyle --config=dev/tox.ini $DOC_PATHS_TO_CHECK >> "$PYDOCSTYLE_REPORT_PATH"
-    pydocstyle_status="${PIPESTATUS[0]}"
+    if [ $PYDOCSTYLEVERSION == "2.1.1" ]; then
+        pydocstyle --config=dev/tox.ini $DOC_PATHS_TO_CHECK >> "$PYDOCSTYLE_REPORT_PATH"
+        pydocstyle_status="${PIPESTATUS[0]}"
 
-    if [ "$compile_status" -eq 0 -a "$pydocstyle_status" -eq 0 ]; then
-        lint_status=0
-    else
-        lint_status=1
-    fi
+        if [ "$compile_status" -eq 0 -a "$pydocstyle_status" -eq 0 ]; then
+            lint_status=0
+        else
+            lint_status=1
+        fi
 
-    if [ "$lint_status" -ne 0 ]; then
-        echo "pydocstyle checks failed."
-        cat "$PYDOCSTYLE_REPORT_PATH"
-        rm "$PYDOCSTYLE_REPORT_PATH"
-        exit "$lint_status"
+        if [ "$lint_status" -ne 0 ]; then
+            echo "pydocstyle checks failed."
+            cat "$PYDOCSTYLE_REPORT_PATH"
+            rm "$PYDOCSTYLE_REPORT_PATH"
+            exit "$lint_status"
+        else
+            echo "pydocstyle checks passed."
+            rm "$PYDOCSTYLE_REPORT_PATH"
+        fi
     else
-        echo "pydocstyle checks passed."
-        rm "$PYDOCSTYLE_REPORT_PATH"
+        echo "The pydocstyle version needs to be latest 2.1.1"
     fi
 else
   echo >&2 "The pydocstyle command was not found. Skipping pydoc checks for now"
