[SPARK-36989][TESTS][PYTHON] Add type hints data tests
### What changes were proposed in this pull request?

This PR:

- Adds basic data test runner to `dev/lint-python`, using [`typeddjango/pytest-mypy-plugins`](https://github.com/typeddjango/pytest-mypy-plugins)
- Migrates data test cases from `pyspark-stubs`

In case of failure, a message similar to the following one

```
starting mypy annotations test...
annotations passed mypy checks.

starting mypy data test...
annotations failed data checks:
============================= test session starts ==============================
platform linux -- Python 3.9.7, pytest-6.2.5, py-1.10.0, pluggy-1.0.0
rootdir: /path/to/spark/python, configfile: pyproject.toml
plugins: mypy-plugins-1.9.2
collected 37 items

python/pyspark/ml/tests/typing/test_classification.yml ..                [  5%]
python/pyspark/ml/tests/typing/test_evaluation.yml .                     [  8%]
python/pyspark/ml/tests/typing/test_feature.yml .                        [ 10%]
python/pyspark/ml/tests/typing/test_param.yml .                          [ 13%]
python/pyspark/ml/tests/typing/test_readable.yml .                       [ 16%]
python/pyspark/ml/tests/typing/test_regression.yml ..                    [ 21%]
python/pyspark/sql/tests/typing/test_column.yml F                        [ 24%]
python/pyspark/sql/tests/typing/test_dataframe.yml .......               [ 43%]
python/pyspark/sql/tests/typing/test_functions.yml .                     [ 45%]
python/pyspark/sql/tests/typing/test_pandas_compatibility.yml ..         [ 51%]
python/pyspark/sql/tests/typing/test_readwriter.yml ..                   [ 56%]
python/pyspark/sql/tests/typing/test_session.yml .....                   [ 70%]
python/pyspark/sql/tests/typing/test_udf.yml .......                     [ 89%]
python/pyspark/tests/typing/test_context.yml .                           [ 91%]
python/pyspark/tests/typing/test_core.yml .                              [ 94%]
python/pyspark/tests/typing/test_rdd.yml .                               [ 97%]
python/pyspark/tests/typing/test_resultiterable.yml .                    [100%]

=================================== FAILURES ===================================
______________________________ colDateTimeCompare ______________________________
/path/to/spark/python/pyspark/sql/tests/typing/test_column.yml:39:
E   pytest_mypy_plugins.utils.TypecheckAssertionError: Invalid output:
E   Actual:
E     main:20: note: Revealed type is "pyspark.sql.column.Column" (diff)
E   Expected:
E     main:20: note: Revealed type is "datetime.date*" (diff)
E   Alignment of first line difference:
E     E: ...ote: Revealed type is "datetime.date*"
E     A: ...ote: Revealed type is "pyspark.sql.column.Column"
E                                  ^
=========================== short test summary info ============================
FAILED python/pyspark/sql/tests/typing/test_column.yml::colDateTimeCompare -
======================== 1 failed, 36 passed in 56.13s =========================
```

will be displayed.

### Why are the changes needed?

Currently, type annotations are tested primarily for integrity and, to lesser extent, against actual API. Testing against examples is work in progress (SPARK-36997).  Data tests allow us to improve coverage and test negative cases (code, that should fail type checker validation).

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Running linter tests with additions proposed in this PR

Closes #34296 from zero323/SPARK-36989.

Authored-by: zero323 <mszymkiewicz@gmail.com>
Signed-off-by: zero323 <mszymkiewicz@gmail.com>

diff --git a/dev/lint-python b/dev/lint-python
--- a/dev/lint-python
+++ b/dev/lint-python
@@ -22,6 +22,7 @@ MINIMUM_MYPY="0.910"
 MYPY_BUILD="mypy"
 PYCODESTYLE_BUILD="pycodestyle"
 MINIMUM_PYCODESTYLE="2.7.0"
+PYTEST_BUILD="pytest"
 
 PYTHON_EXECUTABLE="${PYTHON_EXECUTABLE:-python3}"
 
@@ -123,10 +124,66 @@ function pycodestyle_test {
     fi
 }
 
-function mypy_test {
+
+function mypy_annotation_test {
     local MYPY_REPORT=
     local MYPY_STATUS=
 
+    echo "starting mypy annotations test..."
+    MYPY_REPORT=$( ($MYPY_BUILD \
+      --config-file python/mypy.ini \
+      --cache-dir /tmp/.mypy_cache/ \
+      python/pyspark) 2>&1)
+    MYPY_STATUS=$?
+
+    if [ "$MYPY_STATUS" -ne 0 ]; then
+        echo "annotations failed mypy checks:"
+        echo "$MYPY_REPORT"
+        echo "$MYPY_STATUS"
+        exit "$MYPY_STATUS"
+    else
+        echo "annotations passed mypy checks."
+        echo
+    fi
+}
+
+
+function mypy_data_test {
+    local PYTEST_REPORT=
+    local PYTEST_STATUS=
+
+    echo "starting mypy data test..."
+
+    $PYTHON_EXECUTABLE -c "import importlib.util; import sys; \
+               sys.exit(0 if importlib.util.find_spec('pytest_mypy_plugins') else 1)"
+
+    if [ $? -ne 0 ]; then
+      echo "pytest-mypy-plugins missing. Skipping for now."
+      return
+    fi
+
+    PYTEST_REPORT=$( (MYPYPATH=python $PYTEST_BUILD \
+      -c python/pyproject.toml \
+      --rootdir python \
+      --mypy-only-local-stub \
+      --mypy-ini-file python/mypy.ini \
+      python/pyspark ) 2>&1)
+
+    PYTEST_STATUS=$?
+
+    if [ "$PYTEST_STATUS" -ne 0 ]; then
+        echo "annotations failed data checks:"
+        echo "$PYTEST_REPORT"
+        echo "$PYTEST_STATUS"
+        exit "$PYTEST_STATUS"
+    else
+      echo "annotations passed data checks."
+      echo
+    fi
+}
+
+
+function mypy_test {
     if ! hash "$MYPY_BUILD" 2> /dev/null; then
         echo "The $MYPY_BUILD command was not found. Skipping for now."
         return
@@ -141,20 +198,10 @@ function mypy_test {
         return
     fi
 
-    echo "starting mypy test..."
-    MYPY_REPORT=$( ($MYPY_BUILD --config-file python/mypy.ini python/pyspark) 2>&1)
-    MYPY_STATUS=$?
-
-    if [ "$MYPY_STATUS" -ne 0 ]; then
-        echo "mypy checks failed:"
-        echo "$MYPY_REPORT"
-        echo "$MYPY_STATUS"
-        exit "$MYPY_STATUS"
-    else
-        echo "mypy checks passed."
-        echo
-    fi
+    mypy_annotation_test
+    mypy_data_test
 }
+
 
 function flake8_test {
     local FLAKE8_VERSION=
