SPARK-1144 Added license and RAT to check licenses.
removed rat source jar from the code base

diff --git a/dev/run-tests b/dev/run-tests
--- a/dev/run-tests
+++ b/dev/run-tests
@@ -36,6 +36,21 @@ fi
 JAVA_VERSION=$($java_cmd -version 2>&1 | sed 's/java version "\(.*\)\.\(.*\)\..*"/\1\2/; 1q')
 [ "$JAVA_VERSION" -ge 18 ] && echo "" || echo "[Warn] Java 8 tests will not run, because JDK version is < 1.8."
 
+export RAT_VERSION=0.10
+export rat_jar=$FWDIR/lib/apache-rat-${RAT_VERSION}.jar
+mkdir -p $FWDIR/lib
+
+source $FWDIR/dev/rat.bash
+
+echo "========================================================================="
+echo "Running Apache RAT checks"
+echo "========================================================================="
+[[ -f "$rat_jar" ]] || acquire_rat_jar || {
+    echo "Download failed. Obtain the rat jar manually and place it at $rat_jar"
+    exit 1
+}
+
+$java_cmd -jar $rat_jar -E $FWDIR/.rat-excludes  -d $FWDIR
 
 echo "========================================================================="
 echo "Running Scala style checks"
